name: Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          
      - name: Build all platforms
        run: make build-all
        
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            packager-macos
            packager.exe
            packager-linux
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
